name: Model Training on GPU

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip'

    - name: Cache HF models
      uses: actions/cache@v4
      with:
        path: ~/.cache/huggingface
        key: huggingface-${{ runner.os }}-${{ hashFiles('**/*.py') }}
        restore-keys: |
          huggingface-${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup CUDA
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libtinfo6 \
          libncurses6 \
          gcc-11 \
          g++-11 \
          dkms
        wget https://developer.download.nvidia.com/compute/cuda/12.1.0/local_installers/cuda_12.1.0_530.30.02_linux.run
        sudo sh cuda_12.1.0_530.30.02_linux.run --toolkit --silent --override
        echo "CUDA_PATH=/usr/local/cuda-12.1" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/usr/local/cuda-12.1/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "/usr/local/cuda-12.1/bin" >> $GITHUB_PATH
        
    - name: Train model
      run: |
        nvidia-smi
        python src/train.py
      
    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/final/
        compression-level: 6 