name: Model Training on GPU

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    container: 
      image: nvidia/cuda:12.1.0-base-ubuntu22.04
      options: --gpus all
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip'

    - name: Cache HF models
      uses: actions/cache@v4
      with:
        path: ~/.cache/huggingface
        key: huggingface-${{ runner.os }}-${{ hashFiles('**/*.py') }}
        restore-keys: |
          huggingface-${{ runner.os }}-

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y python3-pip
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify GPU setup
      run: |
        nvidia-smi
        
    - name: Train model
      run: |
        python src/train.py
      
    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/final/
        compression-level: 6 