name: Model Training on GPU

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'

    - name: Cache HF models
      uses: actions/cache@v3
      with:
        path: ~/.cache/huggingface
        key: huggingface-${{ runner.os }}-${{ hashFiles('**/*.py') }}
        restore-keys: |
          huggingface-${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup CUDA
      uses: Jimver/cuda-toolkit@v0.2.14
      with:
        cuda: '12.1.0'
        
    - name: Train model
      run: |
        python src/train.py
      
    - name: Upload model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: models/final/ 